// This file is @generated by prost-build.
/// Base message wrapper for all Meshara messages
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseMessage {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub message_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "MessageType", tag = "3")]
    pub message_type: i32,
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
    #[prost(bytes = "vec", tag = "5")]
    pub sender_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "7")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "8")]
    pub routing_info: ::core::option::Option<RoutingInfo>,
}
/// Routing information for multi-hop routing
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutingInfo {
    #[prost(uint32, tag = "1")]
    pub hop_count: u32,
    #[prost(uint32, tag = "2")]
    pub max_hops: u32,
    #[prost(enumeration = "RouteType", tag = "3")]
    pub route_type: i32,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub next_hop: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub onion_layers: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Private message payload (encrypted)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrivateMessagePayload {
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub return_path: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub ephemeral_public_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// Broadcast payload (signed, not encrypted)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BroadcastPayload {
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Update package (signed by authority)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePackage {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub package_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub changelog: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub checksum: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub required_version: ::prost::alloc::string::String,
    #[prost(bytes = "vec", repeated, tag = "6")]
    pub signatures: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "7")]
    pub authority_public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Query message
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub query_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub query_type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub query_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub response_required: bool,
    #[prost(uint32, tag = "5")]
    pub timeout_ms: u32,
}
/// Response message
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResponseMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub query_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub response_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ResponseCode", tag = "3")]
    pub response_code: i32,
}
/// Message type enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Broadcast = 0,
    PrivateMessage = 1,
    UpdatePackage = 2,
    Query = 3,
    Response = 4,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Broadcast => "BROADCAST",
            Self::PrivateMessage => "PRIVATE_MESSAGE",
            Self::UpdatePackage => "UPDATE_PACKAGE",
            Self::Query => "QUERY",
            Self::Response => "RESPONSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BROADCAST" => Some(Self::Broadcast),
            "PRIVATE_MESSAGE" => Some(Self::PrivateMessage),
            "UPDATE_PACKAGE" => Some(Self::UpdatePackage),
            "QUERY" => Some(Self::Query),
            "RESPONSE" => Some(Self::Response),
            _ => None,
        }
    }
}
/// Route type enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RouteType {
    Direct = 0,
    Bridge = 1,
    OnionRouted = 2,
}
impl RouteType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Direct => "DIRECT",
            Self::Bridge => "BRIDGE",
            Self::OnionRouted => "ONION_ROUTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECT" => Some(Self::Direct),
            "BRIDGE" => Some(Self::Bridge),
            "ONION_ROUTED" => Some(Self::OnionRouted),
            _ => None,
        }
    }
}
/// Response code enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseCode {
    Success = 0,
    NotFound = 1,
    Error = 2,
    Timeout = 3,
    Unauthorized = 4,
}
impl ResponseCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Success => "SUCCESS",
            Self::NotFound => "NOT_FOUND",
            Self::Error => "ERROR",
            Self::Timeout => "TIMEOUT",
            Self::Unauthorized => "UNAUTHORIZED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUCCESS" => Some(Self::Success),
            "NOT_FOUND" => Some(Self::NotFound),
            "ERROR" => Some(Self::Error),
            "TIMEOUT" => Some(Self::Timeout),
            "UNAUTHORIZED" => Some(Self::Unauthorized),
            _ => None,
        }
    }
}
