// This file is @generated by prost-build.
/// Base message wrapper for all Meshara messages (Phase 1)
/// Field allocation strategy:
/// - 1-10: Core fields (used)
/// - 11-20: Reserved for future core extensions
/// - 21-30: Reserved for metadata extensions
/// - 31-50: Reserved for future use
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseMessage {
    /// Protocol version (currently 1)
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// Unique message identifier (16 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub message_id: ::prost::alloc::vec::Vec<u8>,
    /// Type of message payload
    #[prost(enumeration = "MessageType", tag = "3")]
    pub message_type: i32,
    /// Unix timestamp (milliseconds)
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
    /// Sender's Ed25519 public key (32 bytes)
    #[prost(bytes = "vec", tag = "5")]
    pub sender_public_key: ::prost::alloc::vec::Vec<u8>,
    /// Serialized message payload
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Ed25519 signature (64 bytes)
    #[prost(bytes = "vec", tag = "7")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Multi-hop routing information
    #[prost(message, optional, tag = "8")]
    pub routing_info: ::core::option::Option<RoutingInfo>,
}
/// Routing information for multi-hop routing (Phase 1, used in Phase 4)
/// Field allocation: 1-10 used, 11-20 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoutingInfo {
    /// Current hop count
    #[prost(uint32, tag = "1")]
    pub hop_count: u32,
    /// Maximum allowed hops
    #[prost(uint32, tag = "2")]
    pub max_hops: u32,
    /// Type of routing
    #[prost(enumeration = "RouteType", tag = "3")]
    pub route_type: i32,
    /// Next hop node ID (32 bytes)
    #[prost(bytes = "vec", optional, tag = "4")]
    pub next_hop: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// Encrypted onion routing layers
    #[prost(bytes = "vec", optional, tag = "5")]
    pub onion_layers: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// Private message payload (encrypted) (Phase 1)
/// Field allocation: 1-5 used, 6-10 reserved for encryption, 11-20 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PrivateMessagePayload {
    /// Encrypted message content
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// Encrypted return routing info
    #[prost(bytes = "vec", tag = "2")]
    pub return_path: ::prost::alloc::vec::Vec<u8>,
    /// X25519 ephemeral public key (32 bytes)
    #[prost(bytes = "vec", tag = "3")]
    pub ephemeral_public_key: ::prost::alloc::vec::Vec<u8>,
    /// ChaCha20-Poly1305 nonce (12 bytes)
    #[prost(bytes = "vec", tag = "4")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// Broadcast payload (signed, not encrypted) (Phase 1)
/// Field allocation: 1-5 used, 6-15 reserved
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BroadcastPayload {
    /// Message content (plaintext)
    #[prost(bytes = "vec", tag = "1")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// MIME type (e.g., "text/plain", "application/json")
    #[prost(string, tag = "2")]
    pub content_type: ::prost::alloc::string::String,
    /// Custom metadata key-value pairs
    #[prost(map = "string, string", tag = "3")]
    pub metadata:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// Update package (signed by authority) (Phase 1)
/// Field allocation: 1-10 used, 11-20 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePackage {
    /// Semantic version (e.g., "1.2.3")
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Compressed update binary
    #[prost(bytes = "vec", tag = "2")]
    pub package_data: ::prost::alloc::vec::Vec<u8>,
    /// Human-readable changelog
    #[prost(string, tag = "3")]
    pub changelog: ::prost::alloc::string::String,
    /// Blake3 hash of package_data
    #[prost(bytes = "vec", tag = "4")]
    pub checksum: ::prost::alloc::vec::Vec<u8>,
    /// Minimum version required
    #[prost(string, tag = "5")]
    pub required_version: ::prost::alloc::string::String,
    /// Ed25519 signatures (64 bytes each)
    #[prost(bytes = "vec", repeated, tag = "6")]
    pub signatures: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Authority public keys (32 bytes each)
    #[prost(bytes = "vec", repeated, tag = "7")]
    pub authority_public_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Query message (Phase 1)
/// Field allocation: 1-10 used, 11-20 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct QueryMessage {
    /// Unique query identifier (16 bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub query_id: ::prost::alloc::vec::Vec<u8>,
    /// Query type (e.g., "peer_info", "update_check")
    #[prost(string, tag = "2")]
    pub query_type: ::prost::alloc::string::String,
    /// Query parameters (serialized)
    #[prost(bytes = "vec", tag = "3")]
    pub query_data: ::prost::alloc::vec::Vec<u8>,
    /// Whether response is required
    #[prost(bool, tag = "4")]
    pub response_required: bool,
    /// Response timeout in milliseconds
    #[prost(uint32, tag = "5")]
    pub timeout_ms: u32,
}
/// Response message (Phase 1)
/// Field allocation: 1-5 used, 6-15 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResponseMessage {
    /// Matching query identifier
    #[prost(bytes = "vec", tag = "1")]
    pub query_id: ::prost::alloc::vec::Vec<u8>,
    /// Response payload (serialized)
    #[prost(bytes = "vec", tag = "2")]
    pub response_data: ::prost::alloc::vec::Vec<u8>,
    /// Response status code
    #[prost(enumeration = "ResponseCode", tag = "3")]
    pub response_code: i32,
}
/// Route advertisement for route discovery (Phase 4)
/// Field allocation: 1-5 used, 6-15 reserved
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouteAdvertisement {
    /// List of known routes
    #[prost(message, repeated, tag = "1")]
    pub routes: ::prost::alloc::vec::Vec<RouteEntry>,
}
/// Route entry submessage (Phase 4)
/// Field allocation: 1-5 used, 6-15 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RouteEntry {
    /// Node's public key (32 bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub node_id: ::prost::alloc::vec::Vec<u8>,
    /// Hops to reach this node
    #[prost(uint32, tag = "2")]
    pub hop_count: u32,
    /// Unix timestamp (milliseconds)
    #[prost(int64, tag = "3")]
    pub last_seen: i64,
}
/// Acknowledgment for reliable delivery (Phase 4)
/// Field allocation: 1-5 used, 6-15 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Acknowledgment {
    /// ID of message being acknowledged
    #[prost(bytes = "vec", tag = "1")]
    pub message_id: ::prost::alloc::vec::Vec<u8>,
    /// Whether delivery was successful
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// Error description if failed
    #[prost(string, optional, tag = "3")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
}
/// Update announcement for update distribution (Phase 5)
/// Field allocation: 1-10 used, 11-20 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAnnouncement {
    /// Update version string
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Unique update identifier (16 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub update_id: ::prost::alloc::vec::Vec<u8>,
    /// Total size in bytes
    #[prost(uint64, tag = "3")]
    pub size: u64,
    /// Blake3 hash of complete update
    #[prost(bytes = "vec", tag = "4")]
    pub checksum: ::prost::alloc::vec::Vec<u8>,
    /// Authority signatures
    #[prost(bytes = "vec", repeated, tag = "5")]
    pub signatures: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Update request for update distribution (Phase 5)
/// Field allocation: 1-5 used, 6-15 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateRequest {
    /// Update being requested
    #[prost(bytes = "vec", tag = "1")]
    pub update_id: ::prost::alloc::vec::Vec<u8>,
    /// Specific chunk index
    #[prost(uint32, tag = "2")]
    pub chunk_index: u32,
}
/// Update chunk for update distribution (Phase 5)
/// Field allocation: 1-10 used, 11-20 reserved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateChunk {
    /// Update identifier
    #[prost(bytes = "vec", tag = "1")]
    pub update_id: ::prost::alloc::vec::Vec<u8>,
    /// Current chunk index
    #[prost(uint32, tag = "2")]
    pub chunk_index: u32,
    /// Total number of chunks
    #[prost(uint32, tag = "3")]
    pub total_chunks: u32,
    /// Chunk data
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Blake3 hash of this chunk
    #[prost(bytes = "vec", tag = "5")]
    pub chunk_hash: ::prost::alloc::vec::Vec<u8>,
}
/// Message type enumeration
/// Phase 1-3 types (0-4) are implemented in MVP core
/// Phase 4 types (5-6) add routing features
/// Phase 5 types (7-9) add update distribution features
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    /// Phase 1-3: Core message types
    ///
    /// Public broadcast message
    Broadcast = 0,
    /// Encrypted private message
    PrivateMessage = 1,
    /// Signed software update
    UpdatePackage = 2,
    /// Query to authority node
    Query = 3,
    /// Response from authority node
    Response = 4,
    /// Phase 4: Routing extensions
    ///
    /// Route discovery and sharing
    RouteAdvertisement = 5,
    /// Message delivery confirmation
    Acknowledgment = 6,
    /// Phase 5: Update distribution extensions
    ///
    /// Lightweight update notification
    UpdateAnnouncement = 7,
    /// Request for update chunk
    UpdateRequest = 8,
    /// Update data chunk
    UpdateChunk = 9,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Broadcast => "BROADCAST",
            Self::PrivateMessage => "PRIVATE_MESSAGE",
            Self::UpdatePackage => "UPDATE_PACKAGE",
            Self::Query => "QUERY",
            Self::Response => "RESPONSE",
            Self::RouteAdvertisement => "ROUTE_ADVERTISEMENT",
            Self::Acknowledgment => "ACKNOWLEDGMENT",
            Self::UpdateAnnouncement => "UPDATE_ANNOUNCEMENT",
            Self::UpdateRequest => "UPDATE_REQUEST",
            Self::UpdateChunk => "UPDATE_CHUNK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BROADCAST" => Some(Self::Broadcast),
            "PRIVATE_MESSAGE" => Some(Self::PrivateMessage),
            "UPDATE_PACKAGE" => Some(Self::UpdatePackage),
            "QUERY" => Some(Self::Query),
            "RESPONSE" => Some(Self::Response),
            "ROUTE_ADVERTISEMENT" => Some(Self::RouteAdvertisement),
            "ACKNOWLEDGMENT" => Some(Self::Acknowledgment),
            "UPDATE_ANNOUNCEMENT" => Some(Self::UpdateAnnouncement),
            "UPDATE_REQUEST" => Some(Self::UpdateRequest),
            "UPDATE_CHUNK" => Some(Self::UpdateChunk),
            _ => None,
        }
    }
}
/// Route type enumeration (Phase 1, used in Phase 4)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RouteType {
    /// Direct connection to recipient
    Direct = 0,
    /// Routed through bridge node
    Bridge = 1,
    /// Multi-hop onion routing
    OnionRouted = 2,
}
impl RouteType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Direct => "DIRECT",
            Self::Bridge => "BRIDGE",
            Self::OnionRouted => "ONION_ROUTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECT" => Some(Self::Direct),
            "BRIDGE" => Some(Self::Bridge),
            "ONION_ROUTED" => Some(Self::OnionRouted),
            _ => None,
        }
    }
}
/// Response code enumeration (Phase 1)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResponseCode {
    /// Query successful
    Success = 0,
    /// Resource not found
    NotFound = 1,
    /// Server error
    Error = 2,
    /// Query timed out
    Timeout = 3,
    /// Not authorized
    Unauthorized = 4,
}
impl ResponseCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Success => "SUCCESS",
            Self::NotFound => "NOT_FOUND",
            Self::Error => "ERROR",
            Self::Timeout => "TIMEOUT",
            Self::Unauthorized => "UNAUTHORIZED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUCCESS" => Some(Self::Success),
            "NOT_FOUND" => Some(Self::NotFound),
            "ERROR" => Some(Self::Error),
            "TIMEOUT" => Some(Self::Timeout),
            "UNAUTHORIZED" => Some(Self::Unauthorized),
            _ => None,
        }
    }
}
